# Permalinks
permalink:           pretty

# Setup
title:               Mehul Sharma
tagline:             Computer science Sophomore from The LNM Institute Of Information Technology Jaipur .
url:                 http://mehuled.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mehul Sharma
  url:               https://twitter.com/jamigibbs
  email:             mehulcse0209@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jamigibbs/portfolio
google_analytics:    UA-3363703-15
twitter:             jamigibbs
github:              jamigibbs
dribbble:            jamigibbs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
